import pytest
import sys
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)

from project.data.app_data import (
    InlineKeyboardButton,

    ALIBI, DETECTIT,

    _create_inline_buttons)

A_INLINE_BUTTONS_EXP: dict[int, list[list[InlineKeyboardButton]]] = {
    1: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]],
    2: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text='2️⃣✅', callback_data='2 +1 Alibi'),
         InlineKeyboardButton(text='2️⃣❌', callback_data='2 -1 Alibi')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]],
    3: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text='2️⃣✅', callback_data='2 +1 Alibi'),
         InlineKeyboardButton(text='2️⃣❌', callback_data='2 -1 Alibi')],
        [InlineKeyboardButton(text='3️⃣✅', callback_data='3 +1 Alibi'),
         InlineKeyboardButton(text='3️⃣❌', callback_data='3 -1 Alibi'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]],
    4: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text='2️⃣✅', callback_data='2 +1 Alibi'),
         InlineKeyboardButton(text='2️⃣❌', callback_data='2 -1 Alibi')],
        [InlineKeyboardButton(text='3️⃣✅', callback_data='3 +1 Alibi'),
         InlineKeyboardButton(text='3️⃣❌', callback_data='3 -1 Alibi'),
         InlineKeyboardButton(text='4️⃣✅', callback_data='4 +1 Alibi'),
         InlineKeyboardButton(text='4️⃣❌', callback_data='4 -1 Alibi')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]],
    5: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text='2️⃣✅', callback_data='2 +1 Alibi'),
         InlineKeyboardButton(text='2️⃣❌', callback_data='2 -1 Alibi')],
        [InlineKeyboardButton(text='3️⃣✅', callback_data='3 +1 Alibi'),
         InlineKeyboardButton(text='3️⃣❌', callback_data='3 -1 Alibi'),
         InlineKeyboardButton(text='4️⃣✅', callback_data='4 +1 Alibi'),
         InlineKeyboardButton(text='4️⃣❌', callback_data='4 -1 Alibi')],
        [InlineKeyboardButton(text='5️⃣✅', callback_data='5 +1 Alibi'),
         InlineKeyboardButton(text='5️⃣❌', callback_data='5 -1 Alibi'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]],
    6: [[InlineKeyboardButton(text='1️⃣✅', callback_data='1 +1 Alibi'),
         InlineKeyboardButton(text='1️⃣❌', callback_data='1 -1 Alibi'),
         InlineKeyboardButton(text='2️⃣✅', callback_data='2 +1 Alibi'),
         InlineKeyboardButton(text='2️⃣❌', callback_data='2 -1 Alibi')],
        [InlineKeyboardButton(text='3️⃣✅', callback_data='3 +1 Alibi'),
         InlineKeyboardButton(text='3️⃣❌', callback_data='3 -1 Alibi'),
         InlineKeyboardButton(text='4️⃣✅', callback_data='4 +1 Alibi'),
         InlineKeyboardButton(text='4️⃣❌', callback_data='4 -1 Alibi')],
        [InlineKeyboardButton(text='5️⃣✅', callback_data='5 +1 Alibi'),
         InlineKeyboardButton(text='5️⃣❌', callback_data='5 -1 Alibi'),
         InlineKeyboardButton(text='6️⃣✅', callback_data='6 +1 Alibi'),
         InlineKeyboardButton(text='6️⃣❌', callback_data='6 -1 Alibi')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='🚫', callback_data='0 +1 Alibi')]]}
D_INLINE_BUTTONS_EXP: dict[int, list[list[InlineKeyboardButton]]] = {
    1: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]],
    2: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text='2️⃣❇️', callback_data='2 +1 Detectit'),
         InlineKeyboardButton(text='2️⃣⭕️', callback_data='2 -1 Detectit')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]],
    3: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text='2️⃣❇️', callback_data='2 +1 Detectit'),
         InlineKeyboardButton(text='2️⃣⭕️', callback_data='2 -1 Detectit')],
        [InlineKeyboardButton(text='3️⃣❇️', callback_data='3 +1 Detectit'),
         InlineKeyboardButton(text='3️⃣⭕️', callback_data='3 -1 Detectit'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]],
    4: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text='2️⃣❇️', callback_data='2 +1 Detectit'),
         InlineKeyboardButton(text='2️⃣⭕️', callback_data='2 -1 Detectit')],
        [InlineKeyboardButton(text='3️⃣❇️', callback_data='3 +1 Detectit'),
         InlineKeyboardButton(text='3️⃣⭕️', callback_data='3 -1 Detectit'),
         InlineKeyboardButton(text='4️⃣❇️', callback_data='4 +1 Detectit'),
         InlineKeyboardButton(text='4️⃣⭕️', callback_data='4 -1 Detectit')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]],
    5: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text='2️⃣❇️', callback_data='2 +1 Detectit'),
         InlineKeyboardButton(text='2️⃣⭕️', callback_data='2 -1 Detectit')],
        [InlineKeyboardButton(text='3️⃣❇️', callback_data='3 +1 Detectit'),
         InlineKeyboardButton(text='3️⃣⭕️', callback_data='3 -1 Detectit'),
         InlineKeyboardButton(text='4️⃣❇️', callback_data='4 +1 Detectit'),
         InlineKeyboardButton(text='4️⃣⭕️', callback_data='4 -1 Detectit')],
        [InlineKeyboardButton(text='5️⃣❇️', callback_data='5 +1 Detectit'),
         InlineKeyboardButton(text='5️⃣⭕️', callback_data='5 -1 Detectit'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]],
    6: [[InlineKeyboardButton(text='1️⃣❇️', callback_data='1 +1 Detectit'),
         InlineKeyboardButton(text='1️⃣⭕️', callback_data='1 -1 Detectit'),
         InlineKeyboardButton(text='2️⃣❇️', callback_data='2 +1 Detectit'),
         InlineKeyboardButton(text='2️⃣⭕️', callback_data='2 -1 Detectit')],
        [InlineKeyboardButton(text='3️⃣❇️', callback_data='3 +1 Detectit'),
         InlineKeyboardButton(text='3️⃣⭕️', callback_data='3 -1 Detectit'),
         InlineKeyboardButton(text='4️⃣❇️', callback_data='4 +1 Detectit'),
         InlineKeyboardButton(text='4️⃣⭕️', callback_data='4 -1 Detectit')],
        [InlineKeyboardButton(text='5️⃣❇️', callback_data='5 +1 Detectit'),
         InlineKeyboardButton(text='5️⃣⭕️', callback_data='5 -1 Detectit'),
         InlineKeyboardButton(text='6️⃣❇️', callback_data='6 +1 Detectit'),
         InlineKeyboardButton(text='6️⃣⭕️', callback_data='6 -1 Detectit')],
        [InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text=' ', callback_data='None'),
         InlineKeyboardButton(text='⛔️', callback_data='0 +1 Detectit')]]}


@pytest.mark.parametrize('group_name, expected', [
    (ALIBI, A_INLINE_BUTTONS_EXP),
    (DETECTIT, D_INLINE_BUTTONS_EXP)])
def test_create_inline_buttons(group_name, expected):
    """Test _create_inline_buttons func from app_data."""
    assert _create_inline_buttons(group_name=group_name) == expected
